# 模型相关的配置文件
MODEL:
  # 模型文件
  WEIGHT: './weights/yolov8s/weights/best.pt'
  # 取值 'cpu'、'0'、 '1'、 '2'、 '3'等 cpu代表以cpu进行推理，0代表使用第0块显卡进行推理
  DEVICE: 'cpu'
  # 阈值
  CONF: 0.4
  # 过滤类别
  CLASSES: None
  # 图片大小
  IMGSIZE: 640


UI:
  # 背景图片
  background: './icon/background.jpg'
  # 主图
  zhutu2: './icon/zhutu2.png'
  # 最上方的名称
  title: '柑橘病害检测识别系统'
  # 名称
  label_title: '柑橘病害检测识别系统'
  # 开始识别按钮背景颜色
  start_button_bg: "48,77,49"
  # 开始识别按钮字体颜色
  start_button_font: "255,255,255"
  # 导出数据按钮颜色
  export_button_bg: "48,77,49"
  # 导出数据按钮字体颜色
  export_button_font: "255,255,255"
  # 图片填充 RGB格式
  padvalue: [ 157,191,175 ]
  # 表格每列的宽度
  column_widths: [ 50, 220, 120, 200, 80, 80, 140 ]
  # 表格中字体的颜色 RGB格式
  column_color: [ 0, 0, 0 ]
  # 个人信息
  label_info_txt: "姓名: Python图像识别                      学号: 20240603                              专业: 人工智能研究院"
  # 个人信息字体颜色 RGB 格式
  label_info_color: "0, 0, 0"
  # 左侧控制区域颜色 RGBA
  label_control_color: "255,255,255, 80"
  # 主图区域颜色
  label_img_color: "255,255,255, 80"
  # 表格相关
  table_widget_info_styles:
    # 表头背景
    header_background_color: "48,77,49"
    # 表头字体
    header_color: "112,63,46"
    # 表格背景
    background_color: "197,190,172"
    # 滑过背景
    item_hover_background_color: "48,77,49"


CONFIG:
  # 摄像头id,如果发现打开摄像头没有画面，修改下面的数值 0 1 2 3 等
  camera_num: 0
  #
  chinese_name: {
    'HLB': '黄龙病',
    'health': '健康',
    'ill': '其他疾病',
    '无目标': '无目标' }

